### ISSUE TITLE
What is 'xlibc'?

### ISSUE THREAD

**Issue by 634750802** [michael-yuji/DiscreteData#5]
Is it a standard system library?

**Comment by michael-yuji** [comment]
@634750802, xlibc is basically same as Darwin(in Apple Platform) and Glibc (in Linux) with some little boost since it contains the following headers does not imported to Glibc
 <ifaddrs.h> // network interfaces
 <sys/epoll.h> // epoll 
 <sys/sendfile.h> // linux sendfile
 <sys/ioctl.h> // linux ioctl
 <sys/inotify.h> // linux inotify

some in Darwin such as
<ifaddrs.h> // network interfaces
<net/if_dl.h> // LINK level socket

**Comment by 634750802** [comment]
Thanks!
